server:
  port: 8301
spring:
  application:
    name: qingfeng-gateway
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: qingfeng
        password: 123456
  cloud:
    gateway:
      routes:
        - id: qingfeng-auth
          uri: lb://qingfeng-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/qingfeng-auth
        - id: qingfeng-Server-System
          uri: lb://qingfeng-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/qingfeng-Server-System
        - id: qingfeng-Server-Test
          uri: lb://qingfeng-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/qingfeng-Server-Test
      default-filters:
        - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8001

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway